targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
      flutter_gen_runner:
        options:
          assets:
            outputs:
              package_parameter_enabled: false
          output: lib/constants/
          integrations:
            flutter_svg: true